### ISSUE TITLE
Failed to download file: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by VirtualKenji** [TomFrankly/pipedream-notion-voice-tasks#10]
I've been getting the following error in the notion portion of my workflow.

It was working fine for weeks without me having changed anything.

Could this be related to Pipedream's new cloud file storage launch?

Error below found below and it happens when new voicenotes are uploaded, as well as generating new test events.

Error
Failed to download file: Response code 404 (Not Found)

Here is the error message:

DETAILS
    at Object.downloadToTmp (file:///tmp/__pdg__/dist/code/0f5c246b7952a2a4d8fb0ab5802d7166cb897a9065e92201a91a31993507bd44/code/Notion-Voice-Notes.mjs:321:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/0f5c246b7952a2a4d8fb0ab5802d7166cb897a9065e92201a91a31993507bd44/code/Notion-Voice-Notes.mjs:1949:5)
    at null.executeComponent (/var/task/launch_worker.js:267:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:764:28)

Here are the previous steps in code:

{ "notion_voice_notes": {}, "trigger": { "event": { ".tag": "data", "client_modified": "2030-01-22T20:39:35Z", "content_hash": "99018994bda76c25de2613871a6c354f1059f879b03786284924ee5568145674", "id": "id:BCd78_dtB7AAAAAAAAAAm2", "is_downloadable": true, "link": "https://ud78r9s3t6c6s7afa545778b4100.dl.cloudstorageusercontent.com/cd/0/get/C-64shEc-r56kB0jBeGPoKnGTbQtlliGe8kZds_3ZXZOcCaXYfMxyd9zLaZ1eaQWDTu1BgQriOM_hxup6T39aCzc8juqf7ftEr4Y0SCwTGdEZcXbnOyPp4aQ9EfryE3p8_N3W2eNUc_WdZQhUfVOpdfZGsQ8fce7p_ynCV71KwB9Dx2cBQkKb4EJ7FZRVmtYUl/file", "name": "sound-sample-10mins.mp3", "path_display": "/Users/sample-sound-10mins.mp3", "path_lower": "/users/sample-sound-10mins.mp3", "rev": "025de20479j6e65000000150r508q9r", "server_modified": "2030-01-22T20:39:35Z", "size": 5200935 }, "context": { "id": "2YyLF55WcjOtqNMELiEEpk3UB4P", "ts": "2023-12-02T04:52:45.531Z", "pipeline_id": null, "workflow_id": "p_brCO6Pa", "deployment_id": "d_EksW6NoW", "source_type": "TRACE", "verified": false, "hops": null, "test": true, "replay": false, "owner_id": "o_bLI1DYR", "platform_version": "3.44.10", "workflow_name": "Notion Voice Notes (Dropbox)", "resume": null, "emitter_id": "dc_x2um18B", "trace_id": "2YyLF55WcjOtqNMELiEEpk3UB4P", "JIT": true, "attachments": {} } } }

Totally awesome workflow and has been changing the game for me.

Thanks so much for putting this together Thomas!

Can't wait to get it going again.

**Comment by TomFrankly** [comment]
@VirtualKenji is this happening only when testing, or during normal runs too? I use Dropbox and I just tested the workflow successfully.

Also, can you make sure your workflow is up to date? https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update

**Comment by VirtualKenji** [comment]
The workflow was updated and it still didn't work.

But I made a new dropbox automation from scratch using the same notion database and everything works fine now.

It is resolved, and I can keep recreating the workflow from scratch if needed.

Thank you @TomFrankly !
