### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'task')

### ISSUE THREAD

**Issue by ChrisChurch89** [TomFrankly/pipedream-notion-voice-tasks#14]
For some reason when I choose the "Task" Property in "Task Name (Required) it comes back with this message and I'm not sure why

**Comment by qumino2** [comment]
Same issue!

**Comment by TomFrankly** [comment]
Hey @qumino2 - can you share a screenshot showing the entire error message?

This repo isn't as actively managed as my other ones, but if I can identify the issue quickly I'll try to help.

**Comment by qumino2** [comment]
@TomFrankly Sorry for the late reply, I solved this problem myself later. The error was caused by not testing the 'trigger' part in the Notion voice task on Pipedream (this step was not mentioned in your tutorial, but it was mentioned in another voice note tutorial, so I was inspired).
