### ISSUE TITLE
Revising Order of Voice Note Summary OR Different Instructions

### ISSUE THREAD

**Issue by ChrisChurch89** [TomFrankly/pipedream-notion-voice-tasks#15]
Hey Tom,

first I just want to say thank you for being such a great resource in the notion community. I wouldn’t have been able to get as far as I did without your tutorials and ultimate brain template.

I wanted to see if it was possible to switch around the order in which the outputs come out for voice note tasks.

For example, I’d rather have the transcription at the bottom of everything so I can have the summary and main takeaways at the top and can reference the entire transcription at the bottom if necessary (if possible to make it a sub-page automatically or inside a toggle that would be great but not important).

Also I wanted to have variations of the workflow for different purposes and wanted to see if and where within the code I can edit it to provide a different prompt. I often take minutes for my company or make recorded calls and would like specific sections created based on the prompt.

I am not much of a coder but can tinker with it based on my VBA and Javascript experience if I knew which sections to reference. Anything helps.

thanks again for all your efforts and appreciate any help or suggestions!

**Comment by TomFrankly** [comment]
Hey @ChrisChurch89!

I'd love to support these requests, but at the moment I'm completely heads-down on new YouTube videos, as well as the launch of our new app, Flylighter: https://flylighter.com/

Once we launch, we'll be starting work on our iOS app, which will have this voice-notes workflow built in with tons of improvements. Re-ordering the summary/transcription/lists shouldn't be a problem there, and we'll also be able to support building multiple workflows with different settings and destinations.

If you want to try making your own changes to this Pipedream workflow, I'll share this starting point: https://pipedream.com/docs/components/actions-quickstart

There is a significant learning curve involved in developing Pipedream actions at the level I'm doing here, but if you can code, I'd bet you can work through it! I've found it very rewarding myself.
