### ISSUE TITLE
Broken Link?

### ISSUE THREAD

**Issue by jpeth** [TomFrankly/pipedream-notion-voice-tasks#16]
Clicking the button "Use This Template" under "Pipedream – Notion Voice Tasks Workflow" doesn work. 
<img width="797" alt="Screenshot 2024-08-07 at 8 41 40 PM" src="https://github.com/user-attachments/assets/ab716feb-9c0e-40b6-8420-69c73fd2c58f">
<img width="660" alt="Screenshot 2024-08-07 at 8 41 19 PM" src="https://github.com/user-attachments/assets/0cb4291b-8914-4590-a93b-94fee35070ac">

**Comment by TomFrankly** [comment]
@jpeth sorry about that! We changed my shortlink domain from thomasfrank.link to go.thomasjfrank.com some time ago. It should be redirecting, but your browser might have a security policy that prevents it from following that many redirects.

Here's the direct link: https://go.thomasjfrank.com/pipedream-notion-voice-tasks/

I've also updated it on that blog post. Thanks for flagging!
