### ISSUE TITLE
Any way to flag the "At time of event" reminder for dates?

### ISSUE THREAD

**Issue by jkendric** [TomFrankly/pipedream-notion-voice-tasks#3]
Such an amazing workflow.  It just works.

I am curious if there is a good way to adda  trigger word or something in the prompts that could set the reminder notification setting. By default it is none and would be very helpful to have it set "at time of event" for some tasks.  Thanks!

**Comment by TomFrankly** [comment]
Thank you!

I would love this feature as well, but so far Notion has not exposed the Reminder feature to their public API. So for now I'm unable to add that, but I'll see if I can get in touch with the API team and get a sense on whether or not that feature is coming.
