### ISSUE TITLE
Type Error: Cannot read properties of undefined (reading 'options')

### ISSUE THREAD

**Issue by achartt** [TomFrankly/pipedream-notion-voice-tasks#8]
I am running into a "Type Error Cannot read properties of undefined (reading 'options')" Error when I select the notes database I made using the PARA Dashboard Tutorial. 
<img width="1490" alt="Screenshot 2023-10-11 at 11 55 33 AM" src="https://github.com/TomFrankly/pipedream-notion-voice-tasks/assets/80549907/69b7df5c-f63e-45cf-8655-93016c4f7122">
Here are the properties for this database:
<img width="1372" alt="Screenshot 2023-10-11 at 11 59 26 AM" src="https://github.com/TomFrankly/pipedream-notion-voice-tasks/assets/80549907/1b7a5f9c-4a3e-4226-95c4-58048acf184b">

I can get it to work if I follow the instructions to the letter but as soon as I try to change the notes database to the one I actually use it won't work. 
<img width="1490" alt="Screenshot 2023-10-11 at 11 56 17 AM" src="https://github.com/TomFrankly/pipedream-notion-voice-tasks/assets/80549907/80644b3c-4eef-47cf-b732-c7059c1c1de8">

I have searched through the common errors FAQ and the GitHub page to see if anyone else is having this issue but I can't even really sort out why this error is coming up.

**Comment by TomFrankly** [comment]
Hey @achartt,

I'm having a hard time reproducing this. Did you build your database from scratch, or did you use the template I provided?

Also, if you refresh the Pipedream builder page, do you have an Update button on the notion_voice_notes component available?

If so, you'll see a red button here (and if you do, you should click it to update):

![CleanShot 2023-10-11 at 12 05 00@2x](https://github.com/TomFrankly/pipedream-notion-voice-tasks/assets/684961/7e6be4f2-dfb0-47f8-9349-c2c95ad8fa8b)

**Comment by TomFrankly** [comment]
@achartt I think I figured it out.

I was able to reproduce this by first choosing a different database that does have a Select property. Then I set the Note Tag option. 

Then I tried switching over to a database that does not have a Select property, and got the error. I think Pipedream must have kept that Note Tag value set, even when I switched the database over.

I believe you should be able to fix this by adding a Select property to your database. Alternatively, you can click my workflow link again to start from scratch, this time making sure to select your PARA notes database first.

Let me know if that doesn't fix it!

**Comment by achartt** [comment]
@TomFrankly I went and checked my select properties and I had named my "tags" property as "type" and changing it to "tags" did make it work correctly. Thanks!

**Comment by TomFrankly** [comment]
Oh that's even stranger! The code doesn't really care about what a property's name is; it's just looking for its type. So there must be something even deeper down that's causing an issue.
