### ISSUE TITLE
Add field to capture URL link back to audio file

### ISSUE THREAD

**Issue by achartt** [TomFrankly/pipedream-notion-voice-tasks#9]
Something I have been doing with my notes in notion is manually linking back to my google drive folder that contains the audio (not for my own voice notes but for my recorded interviews). It would be handy if since we are already capturing that URL data we could include it in a URL property of the note.

**Comment by TomFrankly** [comment]
@achartt you can do that by adding a step to your workflow!

The Notion → Update Page action will let you do this. You can choose the same Parent Database as in the notion_voice_notes step.

Then the Page ID can be found in the notion_voice_notes Exports. It should be `steps.notion_voice_notes.$return_value.notion_response.response.id`

Finally, the link to your audio file is in the trigger's data. For Google Drive, it _should_ be `steps.trigger.event.webViewLink`, but you can browse through the Exports tab in the trigger to find it and hit Copy Path to be sure.

Just tested this myself, and it works well!

You can use the same action to perform nearly any other kind of update you want on the resulting page, or even to grab exported information and do other things with it (e.g. sending yourself an email).

![CleanShot 2023-10-12 at 09 31 15@2x](https://github.com/TomFrankly/pipedream-notion-voice-tasks/assets/684961/8f1325b1-4999-46c3-8236-fe46023fdf92)
